# Generated by Django 3.2.5 on 2021-09-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(default='media/film/poster/cs.jpg', upload_to='Films/poster'),
        ),
    ]
