# Generated by Django 3.2.5 on 2021-09-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links_film',
            name='type',
        ),
        migrations.AddField(
            model_name='links_film',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
