# Generated by Django 3.2.5 on 2021-09-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_film_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='popular',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='film',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
